[package]
name = "tomb_of_heroes_app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Bevy 0.15 graphical application and egui interface for Tomb of Heroes"

[dependencies]
tomb_of_heroes_core = { path = "../tomb_of_heroes_core" }
bevy = { workspace = true }
bevy_egui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zstd = { workspace = true }
rand_xoshiro = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
